language: node_js
node_js:
  - "8"
sudo: false
addons:
  chrome: stable
  firefox: latest
services:
  - xvfb
before_script:
  - export DISPLAY=:99.0
script:
  - npm --silent run deploy-status -- --status pending --message 'Waiting for build'

  - npm --silent run eslint

  - npm --silent run build
  - npm --silent run coverage -- --browsers FirefoxHeadless --webgl-stub --failTaskOnError --suppressPassed

  - travis_wait 20 npm --silent run release -- --concurrency 1
  - npm pack &> /dev/null

  - npm --silent run buildApps

  - npm --silent run deploy-s3 -- -c 'public, max-age=1800' --confirm
  - npm --silent run deploy-status -- --status success --message Deployed

# Various Node.js smoke-screen tests
  - node -e "const Cesium = require('./');"
  - NODE_ENV=development node index.js
  - NODE_ENV=production node index.js

  - npm --silent run cloc
